# 一步到位：拉 Qwen2.5-7B-Instruct，打人设进 Ollama，切主聊模型
# 用法（管理员/普通均可）:
#   powershell -ExecutionPolicy Bypass -File scripts/build-kurisu-stable.ps1
# 可选: -SkipPull  -SetUserEnv

param(
  [switch]$SkipPull,
  [switch]$SetUserEnv,
  [string]$BaseModel = "qwen2.5:7b-instruct",
  [string]$OutName = "kurisu-stable"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Read-Trimmed([string]$path, [int]$maxChars) {
  if (-not (Test-Path $path)) { return "" }
  $t = [IO.File]::ReadAllText($path).Trim()
  if ($t.Length -le $maxChars) { return $t }
  return $t.Substring(0, $maxChars).Trim() + "`n…(截断)"
}

Write-Host "==> base=$BaseModel  out=$OutName"

if (-not $SkipPull) {
  Write-Host "==> ollama pull $BaseModel (首次可能较久)"
  & ollama pull $BaseModel
  if ($LASTEXITCODE -ne 0) { throw "ollama pull failed: $LASTEXITCODE" }
}

$core = Read-Trimmed (Join-Path $root "kurisu_core_prompt.txt") 3500
$voice = Read-Trimmed (Join-Path $root "kurisu_voice.txt") 2200
$rules = Read-Trimmed (Join-Path $root "kurisu_character_rules.txt") 1600

$system = @"
你就是牧濑红莉栖本人。禁止自称 AI/程序/语言模型/助手热线。禁止把思考过程、设定文档、用户分析写成台词。只输出她会对对方说的口语（界面中文由系统处理时听系统约定）。

$core

【口吻】
$voice

【硬规则】
$rules

【生成硬约束】
- 禁止：用户突然/对话历史/首先需要分析/根据设定/作为AI/数据库/旁白括号长篇
- 禁止：JSON、messages、role 字段泄漏
- 默认对方是冈部伦太郎（熟人）；短句为主，像发消息
"@

$dir = Join-Path $root "models\kurisu-stable"
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$modelfile = Join-Path $dir "Modelfile"

$mf = @"
FROM $BaseModel

PARAMETER temperature 0.72
PARAMETER top_p 0.9
PARAMETER repeat_penalty 1.12
PARAMETER num_ctx 4096

SYSTEM `"``"
$system
`"``"
"@

# Ollama Modelfile SYSTEM """ ... """
$mf = @"
FROM $BaseModel

PARAMETER temperature 0.72
PARAMETER top_p 0.9
PARAMETER repeat_penalty 1.12
PARAMETER num_ctx 4096

SYSTEM `"`"`"
$system
`"`"`"
"@

[IO.File]::WriteAllText($modelfile, $mf, [Text.UTF8Encoding]::new($false))
Write-Host "==> wrote $modelfile ($((Get-Item $modelfile).Length) bytes)"

Write-Host "==> ollama create $OutName"
& ollama create $OutName -f $modelfile
if ($LASTEXITCODE -ne 0) { throw "ollama create failed: $LASTEXITCODE" }

$envFile = Join-Path $root ".env"
$lines = @()
if (Test-Path $envFile) {
  $lines = Get-Content $envFile -ErrorAction SilentlyContinue
}
$kv = @{}
foreach ($line in $lines) {
  if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
  $p = $line.Split('=', 2)
  if ($p.Length -eq 2) { $kv[$p[0].Trim()] = $p[1].Trim() }
}
$kv["AMADEUS_CHAT_MODEL"] = $OutName
$kv["AMADEUS_LITE_MODEL"] = $OutName
if (-not $kv.ContainsKey("AMADEUS_TRANSLATE_MODEL")) {
  $kv["AMADEUS_TRANSLATE_MODEL"] = "qwen2.5:3b"
}

$outEnv = New-Object System.Collections.Generic.List[string]
if (Test-Path $envFile) {
  foreach ($line in Get-Content $envFile) {
    if ($line -match '^\s*AMADEUS_CHAT_MODEL\s*=') {
      $outEnv.Add("AMADEUS_CHAT_MODEL=$OutName")
    } elseif ($line -match '^\s*AMADEUS_LITE_MODEL\s*=') {
      $outEnv.Add("AMADEUS_LITE_MODEL=$OutName")
    } else {
      $outEnv.Add($line)
    }
  }
  if (-not ($outEnv | Where-Object { $_ -match '^\s*AMADEUS_CHAT_MODEL\s*=' })) {
    $outEnv.Add("AMADEUS_CHAT_MODEL=$OutName")
  }
  if (-not ($outEnv | Where-Object { $_ -match '^\s*AMADEUS_LITE_MODEL\s*=' })) {
    $outEnv.Add("AMADEUS_LITE_MODEL=$OutName")
  }
} else {
  $outEnv.Add("# generated by build-kurisu-stable.ps1")
  $outEnv.Add("AMADEUS_CHAT_MODEL=$OutName")
  $outEnv.Add("AMADEUS_LITE_MODEL=$OutName")
  $outEnv.Add("AMADEUS_TRANSLATE_MODEL=qwen2.5:3b")
}
[IO.File]::WriteAllLines($envFile, $outEnv, [Text.UTF8Encoding]::new($false))
Write-Host "==> updated $envFile"

if ($SetUserEnv) {
  [Environment]::SetEnvironmentVariable("AMADEUS_CHAT_MODEL", $OutName, "User")
  [Environment]::SetEnvironmentVariable("AMADEUS_LITE_MODEL", $OutName, "User")
  Write-Host "==> set User env AMADEUS_CHAT_MODEL=$OutName"
}

Write-Host ""
Write-Host "DONE. Next:"
Write-Host "  1) 完全退出 Amadeus / node server.js"
Write-Host "  2) 重新启动（会读 .env / 用户环境变量）"
Write-Host "  3) 主聊应为 $OutName （Qwen2.5-Instruct，非 Qwen3 思维底）"
Write-Host "Smoke: ollama run $OutName `"牧濑，你在吗`""
